// @baseURL_reservations = http://localhost:3000

@baseURL_auth = http://34.111.189.217

@baseURL_reservations = http://34.111.189.217

### Get all reservations 
GET http://34.111.189.217/reservations/


### Get a reservation by id
GET {{baseURL_reservations}}/reservations/6506afe2c18895da718bebd1 

### Create a reservation
POST http://34.111.189.217/reservations/
Content-Type: application/json

{
    "startDate": "12/10/2022",
    "endDate": "12/12/2022",
    "invoiceId": "55555",
    "departureDate": "2021-01-05",
    "placeId": "5ff4e8b9c18895da718bebcf",
    "charge": {
        "amount": 100,
        "card": {
            "number": "4242 4242 4242 4242",
            "exp_month": 12,
            "exp_year": 2027,
            "cvc": 567
        }
    }
}

### Create a reservation PCI
POST {{baseURL_reservations}}/reservations
Content-Type: application/json

{
    "startDate": "12/10/2022",
    "endDate": "12/12/2022",
    "invoiceId": "55555",
    "departureDate": "2021-01-05",
    "placeId": "5ff4e8b9c18895da718bebcf",
    "charge": {
        "amount": 100
    }
}


### Get all users
GET {{baseURL_auth}}/users

### Create a user
POST {{baseURL_auth}}/users
Content-Type: application/json

{
    "email": "test6@test.com",
    "password": "Password123!"

}

### Login
POST {{baseURL_auth}}/auth/login
Content-Type: application/json

{
    "email": "test3@test.com",
    "password": "Password123!"
}

### Get user
GET {{baseURL_auth}}/users

### Get health
GET {{baseURL_auth}}/
