@baseURL = http://localhost:3000

### Get all reservations 
GET {{baseURL}}/reservations


### Get a reservation by id
GET {{baseURL}}/reservations/6506afe2c18895da718bebd1 

### Create a reservation
POST {{baseURL}}/reservations
Content-Type: application/json

{
    "startDate": "21/12/2022",
    "endDate": "31/12/2022",
    "invoiceId": "55555",
    "departureDate": "2021-01-05",
    "placeId": "5ff4e8b9c18895da718bebcf"

}