// @baseURL_reservations = http://localhost:3000

// LOCAL
@baseURL_auth = http://localhost:3001
@baseURL_reservations = http://localhost:3000

// GCP
// @baseURL_auth = http://34.111.114.178
// @baseURL_reservations = http://34.111.114.178


### Get all reservations 
GET {{baseURL_reservations}}/reservations/


### Get a reservation by id
GET {{baseURL_reservations}}/reservations/6506afe2c18895da718bebd1 

### Create a reservation
POST http://34.111.114.178/reservations/
Content-Type: application/json

{
    "startDate": "12/10/2022",
    "endDate": "12/12/2022",
    "invoiceId": "55555",
    "departureDate": "2021-01-05",
    "placeId": "5ff4e8b9c18895da718bebcf",
    "charge": {
        "amount": 100,
        "card": {
            "number": "4242 4242 4242 4242",
            "exp_month": 12,
            "exp_year": 2027,
            "cvc": 567
        }
    }
}

### Get all users
GET {{baseURL_auth}}/users

### Create a user
POST {{baseURL_auth}}/users
Content-Type: application/json

{
    "email": "test35@test.com",
    "password": "Password123!",
    "roles": [{
        "name": "Admin"
    }]
}

### Login
POST {{baseURL_auth}}/auth/login/
Content-Type: application/json

{
    "email": "test20@test.com",
    "password": "Password123!"
}

### Get user
GET {{baseURL_auth}}/users

### Get health
GET {{baseURL_auth}}/
