apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payments
  name: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - image: me-west1-docker.pkg.dev/sleepr-399710/payments/production
        name: payments
        ports:
          - containerPort: 3001
        env:
          - name: TCP_PORT
            value: "3001"
          - name: NOTIFICATIONS_HOST
            value: notifications
          - name: NOTIFICATIONS_PORT
            value: "3000"    
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: connectionString
          - name: RABBITMQ_URI
            valueFrom:
              secretKeyRef:
                name: rabbitmq
                key: connectionString      
          - name: STRIPE_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: stripe
                key: stripeSecretKey
          - name: STRIPE_SECRET
            valueFrom:
              secretKeyRef:
                name: stripe
                key: stripeSecret              

