apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reservations
  name: reservations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservations
  template:
    metadata:
      labels:
        app: reservations
    spec:
      containers:
      - image: me-west1-docker.pkg.dev/sleepr-399710/reservations/production
        name: reservations
        ports:
        - containerPort: 3004
        - containerPort: 3005
        env:
          - name: HTTP_PORT
            value: "3004"
          - name: TCP_PORT
            value: "3005"
          - name: "AUTH_HOST"
            value: auth-tcp
          - name: "AUTH_PORT"
            value: "3002"
          - name: "PAYMENTS_HOST"
            value: payments
          - name: "PAYMENTS_PORT"
            value: "3001"
          - name: NOTIFICATIONS_HOST
            value: notifications
          - name: NOTIFICATIONS_PORT
            value: "3000"              
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: connectionString
               

